apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: {{ .Values.ingress.keycloak.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: {{ .Values.keycloak.service.name }}
              port:
                number: {{ .Values.ingress.keycloak.port }}