apiVersion: v3
name: OpenTelemetry Helm template
version: 1.0.0
description: Helm chart template for an OpenTelemetry Kubernetes deployment
appVersion: 1.0.0
keywords:
  - devon4j
  - demo
  - quarkus
maintainers:
  - name: devon4j Developer
