# Application configuration
application:
  # Configuration to get the metrics information
  metrics:
    jobname: "metrics-jobname"
    url: "metrics-url"
  
  # Configuration of the application service
  service:
    name: "application-service-name"
    name: "application-service-port"

# Ingress configuration
ingress:
  application:
    host: "application.localhost"
    port: 8080
  jaeger:
    host: "jaeger.localhost"
    port: 16686
  zipkin:
    host: "zipkin.localhost"
    port: 9411
  grafana:
    host: "grafana.localhost"
    port: 3000
