# Keycloak configuration
keycloak:
  image:
    name: "jboss/keycloak"
    version: "latest"

  ports:
    http: 8080
    https: 8443

  service:
    name: "keycloak"
    port: 8080
    targetport: 8080

# Ingress configuration
ingress:
  keycloak:
    host: "keycloak.localhost"
    port: 8080