apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent
data:
  otel-agent-config: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors:
      batch:

    exporters:
      otlp:
        endpoint: "otel-collector.default.svc.cluster.local:4317"
        insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            cors_allowed_origins:
            - http://*
            - https://*

    processors:
        batch:

    exporters:
      logging:
      jaeger:
        endpoint: jaeger-all-in-one.default.svc.cluster.local:14250
        insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [jaeger]
          processors: [batch]
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vmetrics-config
data:
  vMetrics.yaml: |
    scrape_configs:
      - job_name: 'metrics-jobname'
        scrape_interval: 10s
        metrics_path: 'metrics-url'
        static_configs:
          - targets: ['application-service-name:application-service-port']