apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: {{ .Values.grafana.name }}
  name: {{ .Values.grafana.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.grafana.name }}
  template:
    metadata:
      labels:
        component: {{ .Values.grafana.name }}
    spec:
      containers:
        - image: grafana/grafana
          name: grafana
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ .Values.grafana.name }}
  name: {{ .Values.grafana.name }}
spec:
  ports:
    - name: "3000"
      port: {{ .Values.grafana.port }}
      targetPort: 3000
  selector:
    component: {{ .Values.grafana.name }}