apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  #adding azure addon annotation for http application routing 
  annotations:
     kubernetes.io/ingress.class: addon-http-application-routing
spec:
spec:
  rules:
  - host: {{ .Values.ingress.application.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: {{ .Values.application.service.name }}
              port:
                number: {{ .Values.ingress.application.port }}
  - host: {{ .Values.ingress.jaeger.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: jaeger-all-in-one
              port:
                number: {{ .Values.ingress.jaeger.port }}
  - host: {{ .Values.ingress.grafana.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: grafana
              port:
                number: {{ .Values.ingress.grafana.port }}
