apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opentelemetry-ingress
spec:
  rules:
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.application.name }}
                port:
                  number: {{ .Values.application.port }}
      host: {{ .Values.application.host }}
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.grafana.name }}
                port:
                  number: {{ .Values.grafana.port }}
      host: {{ .Values.grafana.host }}
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.jaeger.name }}
                port:
                  number: {{ .Values.jaeger.port }}
      host: {{ .Values.jaeger.host }}      