apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    {{- if contains $.Values.application.cloud "AZURE" }}
      {{ toYaml .Values.ingress.azure.annotations | indent 2 }}
    {{- end }}
spec:
  rules:
  - host: {{ template "ingress.application.host" . }} 
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: {{ .Values.application.service.name }}
              port:
                number: {{ .Values.ingress.application.port }}
  - host: {{ template "ingress.jaeger.host" . }} 
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: jaeger-all-in-one
              port:
                number: {{ .Values.ingress.jaeger.port }}
  - host:  {{ template "ingress.grafana.host" . }} 
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: grafana
              port:
                number: {{ .Values.ingress.grafana.port }}
